name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
        working-directory: BanditTool
      - name: Run tests
        run: npm test
        working-directory: BanditTool

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: success()

    steps:
      - name: Deploy to production
        run: echo "Deployment process starts here..."
        env:
          MY_SECRET_API_KEY: ${{ secrets.MY_SECRET_API_KEY }}
