name: CI/CD Pipeline

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: banditTool

      - name: Run tests
        run: npm test
        working-directory: banditTool

  deploy:
    runs-on: ubuntu-latest
    needs: build
    #TODO: test entfernen und diese zeile einblenden if: success() && github.ref == 'refs/heads/main'
    if: success() && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/Ticket#53')

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to production
        run: echo "Deployment process starts here..."
        env:
          MY_SECRET_API_KEY: ${{ secrets.MY_SECRET_API_KEY }}